import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from constants import * # 确保能访问到 TAU_LAB, THRESHOLD 等常数

# 拟合函数 (从 analysis.py 中复制过来)
def wiggle_fit_function(t, N, A, omega, phi_0):
    """
    N: Normalization constant
    A: Asymmetry parameter
    omega: Anomalous precession frequency (自由参数)
    phi_0: Initial phase
    """
    return N * np.exp(-t / TAU_LAB) * (1 + A * np.cos(omega * t - phi_0))

# --- 从 CSV 加载数据和拟合结果 ---
try:
    # 加载计数数据
    counts_data = pd.read_csv("Counts.csv")
    bin_centers = counts_data['Time_us'].values
    counts = counts_data['Counts'].values

    # 加载拟合结果
    fit_results = pd.read_csv("fit_results.csv")
    fit_N = fit_results[fit_results['Parameter'] == 'N']['Value'].values[0]
    fit_A = fit_results[fit_results['Parameter'] == 'A']['Value'].values[0]
    fit_omega = fit_results[fit_results['Parameter'] == 'omega (rad/us)']['Value'].values[0]
    fit_phi_0 = fit_results[fit_results['Parameter'] == 'phi_0 (rad)']['Value'].values[0]
    popt = [fit_N, fit_A, fit_omega, fit_phi_0] # 重新组合拟合参数

except FileNotFoundError as e:
    print(f"Error: Required CSV file not found: {e}. Please ensure 'Counts.csv' and 'fit_results.csv' are generated by analysis.py.")
    exit()

plot_time = np.linspace(0, TIME_MAX, NUM)
fit_curve = wiggle_fit_function(plot_time, *popt)

# --- 绘制 wiggle plot (带拟合曲线) ---
plt.figure(figsize=(15, 5))
plt.scatter(bin_centers, counts, s=1)
plt.plot(plot_time, fit_curve, 'r-', linewidth=0.5, label="Fit")
plt.xlabel(r'Time in Lab Frame ($\mu s$)', fontsize=12)
plt.ylabel(r'Number of High-Energy Positrons ($N_e$)', fontsize=12)
#plt.yscale('log')
plt.grid(True, which="both", ls="--", alpha=0.5)
plt.legend()
plt.tight_layout()
plt.savefig('plot/1wiggle_line_fit_plot_with_fit.png', dpi=300)
plt.show()

# --- 绘制 wiggle plot (不带拟合曲线) ---
plt.figure(figsize=(15, 5))
plt.scatter(bin_centers, counts, s=1)
plt.xlabel(r'Time in Lab Frame ($\mu s$)', fontsize=12)
plt.ylabel(r'Number of High-Energy Positrons ($N_e$)', fontsize=12)
#plt.yscale('log')
plt.grid(True, which="both", ls="--", alpha=0.5)
plt.tight_layout()
plt.savefig('plot/1wiggle_line_fit_plot.png', dpi=300)
plt.show()

# --- 绘制时间模 100 的 wiggle plot (带拟合曲线) ---
time_mod_data = bin_centers % 100
time_mod_fit = plot_time % 100

plt.figure(figsize=(12, 10))
plt.scatter(time_mod_data, counts, s=1)
plt.scatter(time_mod_fit, fit_curve, s=0.25, color='r', label="Fit")
plt.xlabel("Time mod 100 ($\mu s$)", fontsize=12)
plt.ylabel(f"Counts (E > {THRESHOLD} MeV)", fontsize=12)
plt.yscale("log")
plt.grid(True, which="both", ls="--", alpha=0.5)
plt.legend()
plt.tight_layout()
plt.savefig("plot/wiggle_plot_time_mod_100_with_fit.png", dpi=300, bbox_inches='tight')
plt.show()

# --- 绘制时间模 100 的 wiggle plot (不带拟合曲线) ---
plt.figure(figsize=(12, 10))
plt.scatter(time_mod_data, counts, s=1)
plt.xlabel("Time mod 100 ($\mu s$)", fontsize=12)
plt.ylabel(f"Counts (E > {THRESHOLD} MeV)", fontsize=12)
plt.yscale("log")
plt.grid(True, which="both", ls="--", alpha=0.5)
plt.tight_layout()
plt.savefig("plot/wiggle_plot_time_mod_100.png", dpi=300, bbox_inches='tight')
plt.show()
